package Notificaciones;

public enum TipoNotificacion {
    ERROR,
    TAREA_CREADA,
    TAREA_VENCIDA,
    TAREA_PROXIMA,
    ACTIVIDAD_CREADA,
    ACTIVIDAD_INICIADA,
    ACTIVIDAD_COMPLETADA,
    ACTIVIDAD_INTERCAMBIADA,
    ACTIVIDAD_EN_RIESGO,
    PROCESO_CREADO,
    PROCESO_INICIADO,
    PROCESO_COMPLETADO,
    PROCESO_EN_RIESGO
}